name: Publish to NPM

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          version: "latest"
      
      - name: Setup NPM
        uses: actions/setup-node@v5
        # using sudo because of https://github.com/actions/setup-node/issues/324#issuecomment-970306807
      - run: sudo npm install -g npm@latest # npm 11.5.1 or later is required for OIDC
      - run: echo npm version $(npm --version)

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Show bun debug values
        run: bun --revision
      - run: uname -mprs

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Audit vulnerablities
        run: bun audit

      - name: Build package
        run: bun run build

      - name: Publish to NPM
        # Use NPM instead of bun:
        # https://github.com/oven-sh/bun/issues/22423
        # https://github.com/oven-sh/bun/issues/15601
        run: npm publish 
